config/routes.rb
TwitterForRails::Application.routes.draw do
  root to: 'users#index'
  get '/users/all', to: 'users#all'
  resources :users 
  resources :tweets
  resources :relationships

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/relationships.rb
class Relationships < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets, dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :followers, through: :relationship, source: :followers
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	
	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.image_url = auth.info.image
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def new
		@relationship = Relationships.new
		@user = User.find(params[:followed_user])
		@relationship.follower_id = current_user.id
		@relationship.followed_id = @user.id
		@relationship.save!
		redirect_to root_path, alert: "You followed #{@user.name}"
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def index
		@tweets = current_user.tweets
		@tweet = Tweet.new
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user_id = current_user.id
 
	  @tweet.save!
	    redirect_to root_path
	end

	def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy

		redirect_to root_path
	end

	def update
	end

	def show
		@tweet = Tweet.find(param[:id])
	end

	private 

	def tweet_params
		params.require(:tweet).permit(:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		if current_user != nil
			@user = current_user
			@tweets = current_user.tweets
			@tweet = Tweet.new

			@followeds = Relationships.where(:follower_id => current_user.id)
			followeds_ids = @followeds.map(&:followed_id)
			@followed_tweets = Tweet.find_all_by_user_id followeds_ids
			# @followed_tweets = Tweet.where(:user_id => @followeds.find(params[:followed_id]))
		end

	end

	def all
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def follow
		@relationship = Relationships.new
		@user = User.find(params[:id])
		@relationship.follower_id = current_user.id
		@relationship.followed_id = @user.id
		@relationship.save!
		redirect_to root_path, alert: "You followed #{@user.name}"
	end

	def createbio
		@bio = User.update()
	end

	# def create
	# 	@tweet = Tweet.new(tweet_params)
	# 	@tweet.user_id = current_user.id
 
	#   @tweet.save!
	#     redirect_to root_path
	# end

	# def destroy
	#  	@tweet = Tweet.find(params[:id])
	#  	@tweet.destroy

	# 	redirect_to users_path
	# end

	# private 

	 def user_params
	 	params.require(:user).permit(:name, :tweet, :bio)
	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterForRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="user_nav">
	  <% if current_user %>
	    Welcome <strong><%= current_user.name %></strong>!
	    <%= image_tag current_user.image_url %>
	    <%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
	    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h2>tweet index</h2>

<% @tweets.each do |tweet| %>
	<ul>
		<li><%= tweet.body %></li>
	</ul>
<% end %>

<%= simple_form_for @tweet do |f| %>
	<%= f.input :body %><br />
	<%= f.submit "Tweet", class: 'btn btn-primary' %>
<% end %>

app/views/users/all.html.erb
<h2>Users</h2>

<% @users.each do |user| %>
	<ul>
		<li><%= image_tag(user.image_url) %><%= link_to user.name, user %></li>
	</ul>
<% end %>

app/views/users/index.html.erb
<% if @user %>
	<h2>MAI tweets index</h2>

	<% @tweets.each do |tweet| %>
		<ul>
			<li><%= tweet.body %></li>
			<%= link_to 'Delete', tweet_path(tweet),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
		</ul>
	<% end %>

	<%= simple_form_for @tweet do |f| %>
		<%= f.input :body %><br />
		<%= f.submit "Tweet", class: 'btn btn-primary' %>
	<% end %>
	<br />

<h3> Tweets of Peeps I Follow</h3>
<% @followed_tweets.each do |f| %>
	<ul>
	<li><%= f.body%></li>
	</ul>
<% end %>

<br>
	<%= link_to "All Users", users_all_path %>
<% else %>
	<h2>Welcome to Fake Twitter, Yo.</h2>
<% end %>

app/views/users/show.html.erb
<h2><%= image_tag(@user.image_url) %><br /><%= @user.name %></h2>

<h3>Bio: <small><%= @user.bio %></small></h3>
<br>

<%= link_to "Follow Me!", new_relationship_path(:followed_user => @user.id), data: { confirm: 'Are you sure?' } %>
<% @user.tweets.each do |tweet| %>
	<ul>
		<li><%= tweet.body %></li>
	</ul>
<% end %>

<%= link_to "Home", root_path %>